# Generated by Django 4.2.7 on 2024-01-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Email',
            field=models.EmailField(default='hai@gmail.com', max_length=254, verbose_name='hi@gmai.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='Remail',
            field=models.EmailField(default='hai@gmail.com', max_length=254, verbose_name='hi@gmail.com'),
            preserve_default=False,
        ),
    ]
